baseUrl: "ondemand-kube-demo.robocloud.me"

image:
  repository: "robocorp/k8s-on-demand-provisioner"
  tag: latest
  pullPolicy: IfNotPresent
#  pullSecrets: 
#  - name: acr-secret

robocontainer:
  repository: "robocorp/robocontainer"
  tag: latest

ingress:
  enabled: true
  annotations:
     alb.ingress.kubernetes.io/scheme: internet-facing
     alb.ingress.kubernetes.io/target-type: ip
     alb.ingress.kubernetes.io/subnets:  public_subnet1, public_subnet2
     external-dns.alpha.kubernetes.io/hostname: sub_domain
  tls:
    - secretName: k8s-on-demand-provisioner-tls
      hosts:
        - ondemand-kube-demo.robocloud.me

